/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#005234",
        "surface-container-lowest": "#060e20",
        "inverse-primary": "#006c47",
        "on-tertiary-fixed": "#310048",
        "outline": "#87948a",
        "tertiary": "#e9b3ff",
        "on-error": "#690005",
        "secondary-container": "#00a4c3",
        "surface-container": "#171f33",
        "on-secondary-fixed-variant": "#004e5e",
        "surface-bright": "#31394d",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed-variant": "#7300a2",
        "error-container": "#93000a",
        "tertiary-container": "#d680ff",
        "tertiary-fixed": "#f7d8ff",
        "on-tertiary-container": "#5f0087",
        "on-secondary-fixed": "#001f27",
        "secondary": "#5cd5f6",
        "secondary-fixed-dim": "#5cd5f6",
        "primary-container": "#42b883",
        "outline-variant": "#3d4a42",
        "primary-fixed-dim": "#69dca4",
        "on-surface-variant": "#bdcabf",
        "on-tertiary": "#510073",
        "on-secondary": "#003641",
        "surface-container-high": "#222a3d",
        "on-error-container": "#ffdad6",
        "on-background": "#dae2fd",
        "on-primary-container": "#00432a",
        "primary": "#69dca4",
        "secondary-fixed": "#b1ecff",
        "surface-dim": "#0b1326",
        "tertiary-fixed-dim": "#e9b3ff",
        "on-secondary-container": "#00343f",
        "on-surface": "#dae2fd",
        "surface-container-low": "#131b2e",
        "inverse-on-surface": "#283044",
        "on-primary": "#003823",
        "surface": "#0b1326",
        "surface-container-highest": "#2d3449",
        "error": "#ffb4ab",
        "primary-fixed": "#86f9be",
        "background": "#0b1326",
        "inverse-surface": "#dae2fd",
        "surface-tint": "#69dca4",
        "on-primary-fixed": "#002112"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "48px",
        "stack-md": "24px",
        "container-max": "1280px",
        "margin-mobile": "20px",
        "stack-sm": "12px",
        "gutter": "24px",
        "base": "4px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "logo": ["Gugi", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
